import '@radix-ui/themes/styles.css';
import './theme-config.css'
import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import NavBar from "@/app/NavBar";
import {Theme} from '@radix-ui/themes';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className={inter.variable}>
        <Theme appearance="light" accentColor="violet" radius="small">
            <NavBar/>
            <main className='p-5'>
                {children}
            </main>
            {/*<ThemePanel/>*/}
        </Theme>
        </body>
        </html>
    )
}
